### ISSUE TITLE
/data/sx: can't load library 'libnsl.so.0'

### ISSUE THREAD

**Issue by marcogazzola** [zvldz/mgl03_fw#1]
During flash, i recived this error:
/data/sx: can't load library 'libnsl.so.0'

![image](https://user-images.githubusercontent.com/5739630/112230549-4c86f380-8c35-11eb-8a7f-d773bb994dad.png)

**Comment by zvldz** [comment]
what firmware version?

**Comment by zvldz** [comment]
you need version 1.4.7.*

**Comment by zvldz** [comment]
I will fix script

**Comment by zvldz** [comment]
Fixed. Try again.
