### ISSUE TITLE
Wrong firmware file header...trying to flash via UART

### ISSUE THREAD

**Issue by RuiChuz** [zvldz/mgl03_fw#13]
Hello:
my xiaomi gateway 3 has a firmware with version 1.5.1_0032 it doesn't have its telnet port open so in order to get it working in Home Asisstant I'm trying to flash it to mod version 1.5.0_0102 so I follow the instructions written in https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/uart_recovery as follows:

    1.Download mgl03_uart_recovery.ttl
    2.Download and install Tera Term
    3.Run Tera Term
    4.Choose "Serial -> COM port", OK
    5.Choose "Control -> Macro"
    6.Open .mgl03_uart_recovery.ttl file you downloaded in step [1]
    7.Follow on-screen instructions
    8.Perform Factory Reset: after Gateway fully booted click on it's button 10 times repeatedly.

When I get to point 7 Teraterm shows the following message: "Please choose corresponding firmware (mgl03_xxxxxxxxx.uart)"
Then I click in the file root_1.5.0_0102_mod20210816.bin extracted from the zip file. Then Teraterm show me the message "Wrong firmware file header!"
What am I doing wrong?

Thanks to all in advance

**Comment by zvldz** [comment]
You don't need uart to flash the gateway now.
Therefore, you have chosen firmware not specified for uart.
Open telnet with the instruction https://gist.github.com/zvldz/1bd6b21539f84339c218f9427e022709#aqara-hub-e1-zhwg16lm-usb-stick
And flash the gateway using these instructions https://github.com/zvldz/mgl03_fw/tree/main/firmware
The AlexxIT component for Home Assistant can open telnet on the gateway itself if you specify the correct command.
But firmware 1.5.1_0032 is not yet officially supported.
