### ISSUE TITLE
What features does it provides compared to stock fw

### ISSUE THREAD

**Issue by galaxy-fractal** [zvldz/mgl03_fw#15]
Currently I am using stock firmware with the Home Assistant and seems to be working ok. Sometimes I have problems if power goes down and I have manually reopen telnet. So, I wonder what main differences this custom firmware has compared to original stock firmwares?
And if I understand correctly even if I flash with this custom firmware the MI home will continue to work?

**Comment by zvldz** [comment]
MiHome continues to work with custom firmware. And it is even possible to update the firmware via MiHome. The firmware changes are in the firmware folder.

**Comment by galaxy-fractal** [comment]
Thanks!
