### ISSUE TITLE
# -sh: wget: not found , curl: not found 

### ISSUE THREAD

**Issue by MeowRay** [zvldz/mgl03_fw#17]
![QQ截图20220509201623](https://user-images.githubusercontent.com/29674595/167408116-6d277357-add0-4751-a2df-e1c0bc03d03d.jpg)

**Comment by zvldz** [comment]
you must copy commands
you have extra spaces near the quotes

**Comment by MeowRay** [comment]
> you must copy commands you have extra spaces near the quotes

I'm sure I'm not copying wrong, I reset the gateway and went through the process again and it's working fine now
