### ISSUE TITLE
monit binary

### ISSUE THREAD

**Issue by kkmaslowski** [zvldz/mgl03_fw#2]
Hi. Please add monit binary to your firmware https://mmonit.com/monit/
Possible use cases:
- test if socat is running and restart it in case of process absence
- test network connectivity and restart wifi in case of failure
- monitor /var/log/message and do some actions
- etc

**Comment by zvldz** [comment]
You can try 
```
wget "http://master.dl.sourceforge.net/project/mgl03/bin/monit-static?viasf=1" -O /data/monit && chmod +x /data/monit
```
Then I will probably add it to the firmware.

**Comment by kkmaslowski** [comment]
Hi. Great, got it working.

Temporary config file (/data/monitrc):
```
set daemon 60
set logfile syslog facility log_daemon
set eventqueue
        basedir /data/.monit/eventqueue
        slots 100
set statefile /data/.monit/state
set idfile /data/.monit/id
set pidfile /data/.monit/pid
set httpd port 2812
        allow localhost
```

Create /data/.monit dir and start service: 
`/data/monit -c /data/monitrc
`
