### ISSUE TITLE
Correct way to reset Gateway

### ISSUE THREAD

**Issue by igelbro** [zvldz/mgl03_fw#3]
Hello. 
Can you please tell me how to reset the device with cleaning the file system? Pressing the button ten times does not clear the file system.
The problem I have is that after removing the Zigbee devices, I cannot add them to MiHome again. 
The same devices work through a gateway with @AlexIt integration for support zigbee2mqtt.

**Comment by zvldz** [comment]
Pressing the button 10 times will reset the wifi. 
Pressing and holding the button for 10 seconds will reset to factory settings.

**Comment by igelbro** [comment]
Thanks a lot! Will try tonight.

**Comment by igelbro** [comment]
Nope. Neither 10 times pressing nor pressing for 10 seconds cleaning file system of GW.
