### ISSUE TITLE
All zigbee device disconnect

### ISSUE THREAD

**Issue by tiimsvk** [zvldz/mgl03_fw#5]
Hi, please can someone advise.
After the update. (respectively downgrade of the firmware from v1.5.0_0027 to v1.5.0_0026) all zigbee devices were disconnected. I also left enough time to join. With no result. Is there any possibility that it will reconnect at once or do I have to reset all devices one by one and reconnect?

Should I already take this difficult step, is it worth switching the gateway to zigbee2mqtt?
Thank you for your response.

**Comment by zvldz** [comment]
Perhaps the update was not quite successful, since the zigbee devices can not connect. You have to see if Lumi_Z3GatewayHost_MQTT is running.
z2m mode is very sensitive to wifi quality and may crash on unstable connection, for now. ZHA mode is more stable.
