### ISSUE TITLE
1.5.0_0027

### ISSUE THREAD

**Issue by Sihan001** [zvldz/mgl03_fw#6]
1.5.0_0027 已出

**Comment by countrysideboy** [comment]
Looking forward to the new version of it.

**Comment by zvldz** [comment]
1.5.0_0027 and 1.5.0_0026 are the same.
Except for the open telnet and password on 27

**Comment by countrysideboy** [comment]
> 1.5.0_0027 and 1.5.0_0026 are the same.
> Except for the open telnet and password on 27

The official just said the new version fix some known problems.(no more information)
I upgraded it in the mihome app carelessly and I have to downgrade it, though I leave the firmware lock switch on.

**Comment by zvldz** [comment]
Bug fixes, it says in any release description ))
I was comparing the contents of the firmware.
