### ISSUE TITLE
what is the recommended version of firmware?

### ISSUE THREAD

**Issue by kkmaslowski** [zvldz/mgl03_fw#9]
Hi!
1. What is the recommended version of your modified firmware? 
2. Which is more stable?

**Comment by zvldz** [comment]
If you use Home Assistant
1.4.6_0012
1.5.0_0026
If not, you can still try
1.5.0_0102

**Comment by kkmaslowski** [comment]
I use for 2-3 months 1.4.7_0160 with home assistant and zha. Should I upgrade to 1.5.0_0026?

**Comment by zvldz** [comment]
for zha mode is not worth updating

**Comment by kkmaslowski** [comment]
Thanks for answer. Maybe add info about recommended versions in README.md.
